### ISSUE TITLE
error: ‘pow’ was not declared in this scope

### ISSUE THREAD

**Issue by Suvero** [jhakonen/wot-teamspeak-plugin#1]
![1542352](https://user-images.githubusercontent.com/44507538/65838441-57dcb580-e303-11e9-8cef-3b6e2c58a71e.PNG)

After "make package" :/

**Comment by jhakonen** [comment]
Oh, damn, sorry for delay. I didn't realize that creating a new repository to Github doesn't make you automatically watch it as well, so I didn't notice this issue.

Not sure why it doesn't compile for you. But, you can try adding an include for math.h and see if that helps.

Note also, that the Linux build, while it does work, it will not actually communicate with TessuMod at all. This is because the communication atm happens over shared memory, and win32/WINE's shared memory is not accessible from Linux's shared memory (or vice-versa). There's a task for fixing that at: https://github.com/jhakonen/wot-teamspeak-mod/issues/32

**Comment by jhakonen** [comment]
I stumbled on this one when setting up CI pipeline. This should be fixed now.
